<%@ Page Title="" Language="C#" MasterPageFile="~/StudentMainMaster.Master" AutoEventWireup="true" CodeBehind="ChosedCourse.aspx.cs" Inherits="CSsystem.ChosedCourse" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="centercontent">
       
       <%--  <table class="table table-striped" style="text-align:center">
    <thead>
    <tr>
        <th class="auto-style3" style="text-align:center">课程编号</th>
        <th class="auto-style1" style="text-align:center">课程名称</th>
        <th class="auto-style2" style="text-align:center">学分</th>
        <th class="auto-style5" style="text-align:center">教师</th>
        <th class="auto-style6" style="text-align:center">系别</th>
        <th class="auto-style4" style="text-align:center">联系方式</th>
        
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="auto-style3">
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label></td>
        <td class="auto-style1">
            <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label> </td>
        <td class="auto-style2">
            <asp:Label ID="Label3" runat="server" Text="Label"></asp:Label></td>
        <td class="auto-style5">
            <asp:Label ID="Label4" runat="server" Text="Label"></asp:Label></td>
         <td class="auto-style6">
             <asp:Label ID="Label5" runat="server" Text="Label"></asp:Label></td>
         <td class="auto-style4">
             <asp:Label ID="Label6" runat="server" Text="Label"></asp:Label></td>
          
    </tr>
    
    </tbody>
</table>--%>


        <span class="posite" style="color:#3D8031;cursor:default">
        当前位置-&gt;已选课程
     
        <br />
    </span>
        <br />



        <asp:GridView ID="GridView1" runat="server" CssClass="table table-striped" Width="1000px" AutoGenerateDeleteButton="True" OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting" AllowPaging="True" PageSize="3" OnPageIndexChanging="GridView1_PageIndexChanging" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal">
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <PagerTemplate>
                <table width="100%">
                    <tr>
                        <td style="text-align: center">
                            <asp:LinkButton ID="btnFirst" runat="server" CausesValidation="False" CommandArgument="First" CommandName="Page" Text="首页" ForeColor="#3D8031"></asp:LinkButton>
                            <asp:LinkButton ID="btnPrev" runat="server" CausesValidation="False" CommandArgument="Prev" CommandName="Page" Text="上一页" ForeColor="#3D8031"></asp:LinkButton>
                            <asp:LinkButton ID="btnNext" runat="server" CausesValidation="False" CommandArgument="Next" CommandName="Page" Text="下一页" ForeColor="#3D8031"></asp:LinkButton>
                            <asp:LinkButton ID="btnLast" runat="server" CausesValidation="False" CommandArgument="Last" CommandName="Page" Text="尾页" ForeColor="#3D8031"></asp:LinkButton>
                            <asp:TextBox ID="txtNewPageIndex" runat="server" Text="<%# ((GridView)Container.Parent.Parent).PageIndex + 1%>" Width="20px"></asp:TextBox>
                            <asp:LinkButton ID="btnGo" runat="server" CausesValidation="False" CommandArgument="-1" CommandName="Page" Text="GO" ForeColor="#3D8031"></asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>

   </div>
</asp:Content>
